services:
  db:
    container_name: postgres_lic
    image: postgres
    restart: always
    ports:
      - 7070:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
      - POSTGRES_DB=postgres

  adminer:
    container_name: lic-adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080

  keycloak:
    container_name: lic-keycloak
    image: quay.io/keycloak/keycloak:23.0.1
    restart: always
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: 'admin'
      KEYCLOAK_ADMIN_PASSWORD: 'admin'
    command:
      - start-dev
    volumes:
      - ./container-data/keycloak:/opt/keycloak/data/h2

volumes:
  dbvolume: